# Generated by Django 3.2.4 on 2022-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, verbose_name='科目名称')),
                ('username', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('grade', models.IntegerField(verbose_name='分数')),
            ],
        ),
    ]
